version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cemse_prod
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cemse-network

  # Next.js Application
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cemse_prod
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - cemse-network
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run db:seed &&
        npm start
      "

volumes:
  db_data:
    driver: local

networks:
  cemse-network:
    driver: bridge
